### ISSUE TITLE
[Error MSB4062: The "NServiceBus.Persistence.Sql.SqlPersistenceScriptBuilderTask" task could not be loaded from the assembly] after upgrading to version 6.6.1 of the package

### ISSUE THREAD

**Issue by v1adev** [Particular/NServiceBus.Persistence.Sql#1122]
Works fine if I downgrade the package to version 6.6.0 so must be something specific to 6.6.1.

> [error]C:\Users\VssAdministrator\.nuget\packages\nservicebus.persistence.sql\6.6.1\buildTransitive\NServiceBus.Persistence.Sql.targets(23,5): Error MSB4062: The "NServiceBus.Persistence.Sql.SqlPersistenceScriptBuilderTask" task could not be loaded from the assembly C:\Users\VssAdministrator\.nuget\packages\nservicebus.persistence.sql\6.6.1\buildTransitive\..\netstandard\NServiceBus.Persistence.Sql.ScriptBuilderTask.dll. Could not load file or assembly 'C:\Users\VssAdministrator\.nuget\packages\nservicebus.persistence.sql\6.6.1\netstandard\NServiceBus.Persistence.Sql.ScriptBuilderTask.dll'. The system cannot find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by HEskandari** [comment]
Thank you for reporting @v1adev. As David mentioned, this was due to an issue with the .NET SDK packaging. We have released a new patch version ([6.6.2](https://github.com/Particular/NServiceBus.Persistence.Sql/releases/tag/6.6.2)) that contains the fix.
