### ISSUE TITLE
TransactionalSession does not work with outbox using TransactionScope

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.Persistence.Sql#1174]
#### Description

The ambient transaction (`System.Transactions.Transaction.Current`) is `null` after opening a transactional session with the outbox configured to use `TransactionScope` (calling `UseTransactionScope()` on `OutboxSettings`).

When debugging the code, I see that a `TransactionScopeSqlOutboxTransaction` is used and that an `TransactionScope` is created. My initial assessment after looking at the the source code, is that the situation is [similar to this issue](https://github.com/Particular/NServiceBus.Persistence.Sql/issues/504) reported when TransactionScope support was first introduced.

I've created a small repro-app that demonstrates the problem: https://github.com/pardahlman/nsb-transactional-session-repro

#### Expected behavior

The ambient transaction is set.

#### Actual behavior

The ambient transaction is null

#### Versions

`NServiceBus.Persistence.Sql.TransactionalSession` 7.0.0

### Steps to reproduce

Clone repro app and follow the instructions in README

**Comment by andreasohlund** [comment]
We've triaged this as a priority bug and have started work on a fix

**Comment by tmasternak** [comment]
@pardahlman we would like to understand your scenario better and the interaction between your business code and `TransactionalSession`. More specifically, we would like to know how you planned to take advantage of the ambient transaction from your business code: 

* Does your business code assume the existence of ambient transactions? 
* Do you expect the transaction scope to escalate to a distributed transaction? 
* Do you expect to make any changes to your code e.g. passing `SqlConneciton` managed by the `TransactionSession`?
* Do you expect to use `TransactionalSession` in your business code?

If you could provide a code sample (even some sudo code) it would be really helpful.

**Comment by pardahlman** [comment]
Hi @tmasternak,

We are planning to use transactional session in our ASP.NET Core applications where transactionality is required for data writes and message publishing. Today, this is achieved by letting the ASP.NET Core application send a command to itself, handle the HTTP request within a "message handling context", and then reply to itself and return an HTTP response to the waiting caller.

Whenever the business code wants a `DbConnection`, a piece of infrastructure code returns an open connection based on the following logic:

* If the caller is within the ambient transaction created by the outbox, return the outbox connection
* If the caller is within _another_ ambient transaction, it is domain code created a nested transaction scope with either `Suppress` or `RequiresNew`, in which case a new connection will be created.

This logic has been in place for a long time and is considered stable.

See below for answers to your questions. I use "domain code" for code directly related to our business logic and "infrastructure code" for domain agnostic code used in multiple applications/domains

 > Does your business code assume the existence of ambient transactions?

Yes, there are multiple occurrences of nested transaction scopes within the domain code.

> Do you expect the transaction scope to escalate to a distributed transaction?

No, the application runs on .NET 6 in kubernetes where distributed transactions are not supported.

> Do you expect to make any changes to your code e.g. passing SqlConneciton managed by the TransactionSession?

We expect no changes to existing domain code, instead we are planning to replace infrastructure code responsible for sending a command to itself and potentially also parts of the code identifying the ambient transaction created by the outbox (today, this is done in a behavior in the incoming message pipeline, this needs to be moved)
 
> Do you expect to use TransactionalSession in your business code?

It wont be feasible in doman code for some of our older and/or larger systems. They will interact with transactional session through existing infrastructure APIs.

We are currently debating to what extent we want to use `ITransasctionalSession` in domain code for newer applications. I think it is likely that it will be used for publishing messages in our ASP.NET Core applications, but we will still rely on the `ISqlStorageSession` abstraction for database access.

Hope this helps!
