### ISSUE TITLE
Transactional Session Messages not sent when using SQL outbox with TransactionScope

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.Persistence.Sql#1193]
#### Description

When using Transactional session with SQL outbox configured to use `TransactionScope`, no messages that are sent/published via `ITransactionalSession` are in fact sent/published to the transport as the session is commited.

#### Expected behavior

Messages sent/published via `ITransactioanlSession` should be sent/published when the session is committed.

#### Actual behavior

No messages are sent/published

#### Versions

`NServiceBus` 8.0.3
`NServiceBus.Persistence.Sql.TransactionalSession` 7.0.1
`NServiceBus.TransactionalSession` 2.0.2

### Steps to reproduce

Clone the [repo app](https://github.com/oskar/TransactionalSessionWithOutbox) and follow instructions for _Reproduce TransactionScope issue_.

#### Additional information

The issue was initially identified using the RabbitMQ transport, but was simplified to LearningTransport in the repo app.

**Comment by danielmarbach** [comment]
@pardahlman thanks for the detailed description and reproduction steps. We have started looking into this issue. I'll keep you posted. In the meantime I have sent a small correction PR to fix parts of the reproduction solution

https://github.com/oskar/TransactionalSessionWithOutbox/pull/1

**Comment by danielmarbach** [comment]
I have raised the persistence counter part https://github.com/Particular/NServiceBus.Persistence.Sql/issues/1198

**Comment by pardahlman** [comment]
Thanks for a detailed explanation of the situation as well as showing how it works in the repo app. I see that you already has a PR in place for fixing #1198. Great and fast work 👌

**Comment by danielmarbach** [comment]
Hi @pardahlman . We've prioritized your issue near the top of our list and will work on it as soon as we can.

**Comment by danielmarbach** [comment]
This has been addressed with https://github.com/Particular/NServiceBus.Persistence.Sql/issues/1198
