### ISSUE TITLE
error MSB4044 when building exe that hosts an endpoint

### ISSUE THREAD

**Issue by macdonald-keith-vmware** [Particular/NServiceBus.Persistence.Sql#123]
For NSB 6, using SQL persistence and Sql.MSBuild, I receive this error when building the EXE that will host the service bus. It generates the SQL, but gives this error.

NServiceBus.Persistence.Sql.MsBuild.targets(22,5): error MSB4044: The "ScriptBuilderTask" task was not given a value for the required parameter "References".

**Comment by SimonCropp** [comment]
@macdonald-keith-vmware sorry to hear. i have a few questions

 1. What version of the SQL persistence nugets are u using?
 1. What form of project system (csproj) are you using? the old version with `packages.config`, or the new version with `<PackageReference` nodes in the csproj?
 1. what version of Visual Studio are you using (including update)?

**Comment by SimonCropp** [comment]
also sometimes VS can aggressively cache msbuild tasks. so i hate to suggest this, but can u try closing all instances of VS and trying again on your solution

**Comment by SimonCropp** [comment]
@macdonald-keith-vmware just checking how you went debugging your problem?

**Comment by SimonCropp** [comment]
Closing this one for now. Let us know if the issue persists.
