### ISSUE TITLE
Support different connection strings for SQL transport and SQL persistence

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.Persistence.Sql#144]
Raised as an [issue on StackOverflow](https://stackoverflow.com/questions/45578950/nservicebus-sql-server-transport-and-sql-persistence-on-different-databases).

When using different connection strings for SQL transport and persistence in transport transaction mode higher than `None`, SQL persistence is attempting to reuse transport connection and fails. 

The issue can be fixed by introducing either `UseSqlTransportConnection`  and default assume people are not using the same connection string, or taking the opposite approach, i.e. introducing `DoNotUseSqlTransportConnection` and by default assume people are using the same connection string.

**Comment by ErikMuir** [comment]
Has this been released yet?

**Comment by SimonCropp** [comment]
@ErikMuir no this is not in the 3.0.0-beta0001. the current plan is a new beta within the next 24 hours. and it will be included in that package

**Comment by nikolic-bojan** [comment]
Hi, was this ever fixed? 
I am on NServiceBus 7.2.0 and get the same issue.
