### ISSUE TITLE
Saga and Outbox SQL persistence combo validation isn't working as the error message suggests

### ISSUE THREAD

**Issue by Niksson** [Particular/NServiceBus.Persistence.Sql#1492]
#### Description
Validation of Sagas and Outbox SQL persistence combination (see [`SqlValidateStorageTypeCombinationFeature`](https://github.com/Particular/NServiceBus.Persistence.Sql/blob/master/src/SqlPersistence/SqlValidateStorageTypeCombinationFeature.cs) class) doesn't work as the message suggests - when it's **disabled** for both Sagas and Outbox it still throws an exception. However, the error message suggests that disabling it for both is allowed.

#### Expected behavior
`SqlValidateStorageTypeCombinationFeature` doesn't throw an exception if SQL persistence is turned off for both Saga and Outbox.
OR
`SqlValidateStorageTypeCombinationFeature` throws an exception that suggests that it's only allowed to have SQL persistence on if both Saga and Outbox are enabled

#### Actual behavior
`SqlValidateStorageTypeCombinationFeature` throws an exception when SQL persistence is disabled for both Saga and Outbox

#### Versions

NServiceBus.Persistence.Sql - 8.0.0
     

### Steps to reproduce

- Create a Web API .NET project
- Create an `EndpointConfiguration` 
- Enable Outbox with `EnableOutbox()` method
- Create a class inheriting from SqlSaga
- Configure endpoint configuration to use non-durable persistence, for example:
```csharp
endpointConfiguration.UsePersistence<NonDurablePersistence, StorageType.Outbox>();
endpointConfiguration.UsePersistence<NonDurablePersistence, StorageType.Sagas>();
```
- Try to launch the project

#### Workarounds
Right now could not find any

#### Possible solutions
The code in `SqlValidateStorageTypeCombinationFeature` class checks if the combination of persistence turned on/off for sagas/outbox is legal:

```c#
  var isSagasEnabledForSqlPersistence = settings.IsFeatureActive(typeof(SqlSagaFeature));
  var isOutboxEnabledForSqlPersistence = settings.IsFeatureActive(typeof(SqlOutboxFeature));
  if (isSagasEnabledForSqlPersistence && isOutboxEnabledForSqlPersistence)
  {
      return;
  }
  throw new Exception("Sql Persistence must be enabled for either both Sagas and Outbox, or neither.");
```
The statement inside `if` only returns true if both sagas and outbox have SQL persistence on.
If we want to make the combination where SQL persistence is disabled for neither also legal, we need to add another condition to the statement:
```c#
if (isSagasEnabledForSqlPersistence && isOutboxEnabledForSqlPersistence || !isSagasEnabledForSqlPersistence && !isOutboxEnabledForSqlPersistence)
{
    return;
}
```

#### Additional information
Right now the integration tests that use NonDurablePersistence in projects that use SqlSagas can't run because of this issue

**Comment by ramonsmits** [comment]
@Niksson Is this related to something you want to accomplish? SqlSaga is a SQLP feature, thus incompatible with `NonDurablePersistence`.

Can I assume you also enabled the persister itself like:

```c#
var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
endpointConfiguration.UsePersistence<NonDurablePersistence, StorageType.Outbox>();
endpointConfiguration.UsePersistence<NonDurablePersistence, StorageType.Sagas>();
```

If so, why not do:

```c#
var persistence = endpointConfiguration.UsePersistence<NonDurablePersistence>();
```

You only want to use SQLP for subscriptions? Which transport are you using as most support native pubsub.

This configuration that enables SQLP but then disable it for outbox and sagas is something I don't understand.

**Comment by Niksson** [comment]
Hello @ramonsmits and thanks for the reply.

To elaborate a little bit on context (and to possibly eliminate the XY problem) - I'm trying to fix integration tests that broke after upgrading NServiceBus from v7 to v9 (and therefore NServiceBus.Persistence.Sql from 1.1.0 to 3.0.0).
We have a method that setups the `EndpointConfiguration` which had these lines while using v7:
```csharp
// Setup persistence
var usePersistence = // get value from IConfiguration
if (!usePersistence)
{
    endpointConfiguration.UsePersistence<InMemoryPersistence>();
}
else
{
    var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
    // rest of the code code to setup SQL connection
}
``` 
Integration tests use `WebApplicationFactory` and set `usePersistence` to false, because in pipeline they don't have an access to any instance of a DMBS (SQL Server in this case).
The integration tests worked fine this way, until we upgraded NServiceBus to v9, following the migration guides.
This led to these changes:
```csharp
var usePersistence = // get value from IConfiguration
if (!usePersistence)
{
    endpointConfiguration.UsePersistence<NonDurablePersistence>(); // This is indeed what I tried to use initially
}
``` 
After upgrading the `SqlValidateStorageTypeCombinationFeature` started throwing the said exception when trying to create the web app via `WebApplicationFactory`.
What I tried then is to explicitly specify that non-durable persistence should be enabled for both outbox and sagas
```csharp
endpointConfiguration.UsePersistence<NonDurablePersistence, StorageType.Outbox>();
endpointConfiguration.UsePersistence<NonDurablePersistence, StorageType.Sagas>();
```
Which didn't help either (and possibly created even more confusion for you).

**Comment by Niksson** [comment]
Read up a little bit and what worked for me is to only enable Oubox if persistence is used (since per documentation Outbox **requires persistent storage**):
```
            var usePersistence = // get from IConfiguration
            if (!usePersistence)
            {
                endpointConfiguration.UsePersistence<NonDurablePersistence>();
            }
            else
            {
                ConfigurePersistenceOnSqlServer(configuration, endpointConfiguration); // Encapsulates SQLP setup
                endpointConfiguration.EnableOutbox();
            }
```
That resolves our X problem (at least for now), but I still believe that the exception message is a little bit misleading here

**Comment by jpalac** [comment]
Will be deployed in NServiceBus.Persistence.Sql 8.1.0
