### ISSUE TITLE
Buffer pooling for saga operations

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.Persistence.Sql#157]
Currently, the saga persister always creates a string containing saga data, by calling `ToJson`. Some dialects, like SQLServer provides capabilities of passing [a size of the parameter](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlparameter.size(v=vs.110).aspx), which can be useful, especially, when combined with some buffer management.

Have you @Particular/sqlpersistence-maintainers considered this optimization? Would it be something you'd be interested into?

https://github.com/Particular/NServiceBus.Persistence.Sql/blob/3b234e1da4652759b982c1c1f6ec39236f62c7a8/src/SqlPersistence/Saga/SagaPersister_Update.cs#L27

**Comment by SzymonPobiega** [comment]
@Scooletz sounds good. I don't think we considered it.

**Comment by MarcinHoppe** [comment]
To add what @SzymonPobiega said, we wouldn't mind a PR 😉.

**Comment by Scooletz** [comment]
Solved by #175
