### ISSUE TITLE
Optimistic concurrency violation exception

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/NServiceBus.Persistence.Sql#158]
Hi,
when I send more than one message to a saga instance I am getting optimistic concurrency violation exceptions and associated immediate retries in the logs (log Level INFO).
I know that this is by design when you are updating the saga data in the handler. But in my case the handler is not updating the saga data (in fact the handler is empty) and I am still getting the exception. In my understanding there should not be optimistic concurrency violations when not updating saga data.
I am using SQL Persistence and SQL Transport in the newest versions. The issue can be reproduced with the following sample:
https://docs.particular.net/samples/sqltransport-sqlpersistence/
I added a IHandleMessages MyMessage to the saga and send 10 MyMessages from the Sender to the saga. I changed the log Level to Info.

Thanks
Tobias

**Comment by DavidBoike** [comment]
Hi @Tobias-Gr,

You're right. SQL Persistence doesn't do any equivalency checking or hashing on the saga data to determine if there has been a change or not. It will always issue an update statement, it doesn't attempt to treat a non-change as a no-op with no update statement issued.

However, I want to explore the other side for a moment. Within the saga handler you could also be sending additional messages, which you would want to be sent atomically with the data update, even if the data update was a no-op.

So consider this: 2 message arrive at roughly the same time and begin processing with the same version of saga data. One message determines that no change to saga data is necessary but a message needs to go out. The other message determines that it needs to modify saga data in such a way that, if the first message were to start over, it would not want to send a message anymore, or it would want to send a different message with different values.

With the saga updating the row either way, one of those messages is going to meet with a concurrency exception and retry. If it treated the saga as a no-op, both those message handlers could commit successfully.

I'm honestly not sure which behavior is more correct - I'd like others in the @Particular/sqlpersistence-maintainers group to weigh in.

**Comment by DavidBoike** [comment]
We've discussed more internally, and we don't intend to make any changes right now because, as you say, the current behavior is correct, it's just inefficient when you know the saga data wouldn't need to be updated each time. In order to allow that efficiency tweak, we'd want it to be an opt-in behavior since it could change the correctness of the behavior as I mentioned above.

But, it's also hard to come up with real-life scenarios that fit the situation I described above, so if you know of any, we would love to hear them, to make sure that if we do design an opt-in feature to allow this optimization, that we design it correctly. Then we might consider implementing in a minor release down the road.

**Comment by Tobias-Gr** [comment]
Hi @DavidBoike ,
thanks for your answer.
The opt-in behavior would be fine for us (some kind of property that we set in handlers that don't write to SagaData).
One example from our code is: We have a saga that requests timeouts in order to periodically call a webservice (via sending a message to a separate handler). The saga gets a reply-message from the handler with the webservice-result. Depending on the result the saga requests a new timeout (and does not write to the SagaData) or it writes to the SagaData and then does something else.
