### ISSUE TITLE
Add Oracle Support

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#17]

**Comment by DavidBoike** [comment]
Completed in 2.1.0

* [Release notes](https://github.com/Particular/NServiceBus.Persistence.Sql/releases/tag/2.1.0)
* [Announcement](https://groups.google.com/forum/#!topic/particularsoftware/XXvdEME7uFo)
* [Connection details in docs](https://docs.particular.net/nservicebus/sql-persistence/#usage-oracle)
* [Oracle-specific caveats](https://docs.particular.net/nservicebus/sql-persistence/oracle-caveats) dealing mostly with table length restrictions
