### ISSUE TITLE
move acceptence tests back into main solution

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#18]
and make them run for all sql variants

**Comment by SzymonPobiega** [comment]
@SimonCropp have you figured out how to do it without locking the assemblies?

**Comment by SimonCropp** [comment]
Yeah. I will take this one

**Comment by SimonCropp** [comment]
done https://github.com/Particular/NServiceBus.Persistence.Sql/commit/1e82682902d8b1a6a62ff1a6afec881d34088a79
