### ISSUE TITLE
Add startup diagnostics info

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.Persistence.Sql#190]
We can now capture [startup diagnostic information](https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics).

We need to decide what info is worth logging and implement it.

Connects to https://github.com/Particular/DotNetCoreLaunch/issues/78

**Comment by ramonsmits** [comment]
Please execute `SELECT @@VERSION` on SQL Server to capture SQL Server version info. This helps us to understand if the customer is running with the latest patches on their SQL box.

**Comment by DavidBoike** [comment]
Just want to raise that executing a query against a database is an extra level of risk. Could affect startup time, or if it blew up or was disallowed by server permissions, could prohibit the endpoint from starting.

**Comment by weralabaj** [comment]
I've looked around to see what kind of information is stored using this feature, for example:
- Containers => whether the existing or new container is used within NSB.
- Serializer => its full name, version and content type.
- FeatureActivator =>[FeatureDiagnosticData](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureDiagnosticData.cs)
- Audit feature => audit queue address, ttbr value
- Recovaribility feature => values in config (# of retries, frequency, etc.)
- MSMQ transport => [here](https://github.com/Particular/NServiceBus.Transport.Msmq/blob/0e14e4522329533c262e08e13ded07714d69cdff/src/NServiceBus.Transport.Msmq/MsmqTransportInfrastructure.cs#L133)
- Hosting => [here](https://github.com/Particular/NServiceBus/blob/5f4a7b552783318f244f191746dffb258235a0fa/src/NServiceBus.Core/Hosting/HostInformationFeature.cs#L53)

**Comment by weralabaj** [comment]
For the SQL persistence I propose to add info about:
- Selected dialect
- Version
- Subscriptions caching
- Outbox settings (if outbox enabled)
- Info whether multiple connection strings are used (not log connection string itself, but yes/no whether they were used per feature)
- Info whether custom schema is used (not log the schema value itself, but yes/no whether it's configured)
- Info whether SqlServer Transport connection is re-used (`DoNotUseSqlServerTransportConnection`)
- Info whether JsonBParameterModifier is used
- Sagas:
   - Custom JSonSettings usage (used/not used)? Do we need/want detailed data here?
   - [Version/type specific deserialization settings](https://docs.particular.net/persistence/sql/saga#json-net-settings-custom-settings-version-type-specific-deserialization-settings), custom reader, custom writer (used/not used)?

**Comment by weralabaj** [comment]
@Particular/sqlpersistence-maintainers Comments for the above? Anything to add/skip?

**Comment by SzymonPobiega** [comment]
@weralabaj sounds good

**Comment by tmasternak** [comment]
@weralabaj looks good. If we do pesimistic concurrency issue #286 this should get added to the info as well.

**Comment by SzymonPobiega** [comment]
@tmasternak the pessimistic concurrency won't be an opt-in (or opt-out) feature. I will be always turned on.

**Comment by weralabaj** [comment]
That was done
