### ISSUE TITLE
Smoke test v7 persistence samples

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.Persistence.Sql#191]
As per [comment](https://github.com/Particular/docs.particular.net/issues/2778#issuecomment-337469636) seems the samples were not smoke tested after upgrade, we need to do it.

**Comment by weralabaj** [comment]
- [ ] https://docs.particular.net/samples/saga/migration/?version=core_7
- [ ] https://docs.particular.net/samples/sql-persistence/transitioning-correlation-ids/
- [ ] https://docs.particular.net/samples/sql-persistence/saga-rename/?version=sqlpersistence_3
- [ ] https://docs.particular.net/samples/saga/sql-sagafinder/
- [ ] https://docs.particular.net/samples/sql-persistence/simple/
- [ ] https://docs.particular.net/samples/outbox/sql/
- [ ] https://docs.particular.net/samples/sqltransport-sqlpersistence/

**Comment by SzymonPobiega** [comment]
@weralabaj I think this has been done, right?

**Comment by weralabaj** [comment]
yes, but if we update core to the newest version then needs to be repeated, that's why I didn't tick the checkboxes

**Comment by SimonCropp** [comment]
i updated to NSB beta 12 and released SQL persistence 3.0.0-beta0005 to myget

**Comment by SimonCropp** [comment]
i smoke tested 3 of the samples

**Comment by weralabaj** [comment]
tested three more samples, I need some assistance from @SzymonPobiega re saga migration sample, seems there were some accidental changes or description needs to be clarified. the issue is not with a sql persistence though, but the sample itself. should we raise and track it separately then and consider SQL persistence to be RC-ready?

**Comment by weralabaj** [comment]
After consulting with Szymon we decided to raise a separate issue for fixing sample, the problem is not related to SQL persistence, but samples need to be fixed. That shouldn't be a blocker for beta/RC though.
