### ISSUE TITLE
Issue when using custom schema and Oracle

### ISSUE THREAD

**Issue by lnu** [Particular/NServiceBus.Persistence.Sql#192]
The generated queries don't contain the schema before the table name. The script to generate the tables does not containt it either.
Is there any plan to support custom schema with Oracle?

**Comment by MarcinHoppe** [comment]
@lnu A schema in Oracle is roughly equivalent to a catalog and one of its schemas in SQL Server 
 ([see here](https://stackoverflow.com/questions/5365368/what-is-the-difference-between-an-oracle-and-microsoft-schema)).

Our goal was to support putting NServiceBus database objects in a separate schema on SQL Server. Databases that do not support a similar concept are ignoring this parameter, at least in version 2 of the transport. In the upcoming version 3 of the transport we only provide the `Schema()` configuration method for SQL Server so it will not even be possible to configure a custom schema on Oracle.

Can you describe what are you trying to achieve with custom schemas on Oracle?

**Comment by lnu** [comment]
I’m connecting to oracle with a read only user which has grants on the real schema. So the tables are in schema xxx and I’m accessing them with user xxx_ro(which has select/insert/update grants only)
I’ve forked the project and did the needed changes to make it work. I’ll try it tomorrow.

**Comment by SzymonPobiega** [comment]
@lnu Let us know how it worked.

**Comment by lnu** [comment]
It works well for my scenario.
https://github.com/Particular/NServiceBus.Persistence.Sql/pull/197

**Comment by MarcinHoppe** [comment]
@lnu Many thanks for submitting the PR. Well done!

We will release this change as a part of 2.2.0 release of the persistence.
