### ISSUE TITLE
Add ability to promote SQL scripts to source directory

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#21]
https://docs.particular.net/nservicebus/sql-persistence/#script-creation-promotion

**Comment by SimonCropp** [comment]
@weralabaj @SzymonPobiega this is a XS that would be a good one for someone to get some knowledge of MSBuild. any takers for a PR?

**Comment by weralabaj** [comment]
I'm interested, but can start tomorrow, if nobody else beats me up to this, OK?
