### ISSUE TITLE
Add Outbox config options similar to other persistences

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus.Persistence.Sql#210]
As raised here https://github.com/Particular/docs.particular.net/issues/3383

PoA:
- [x] Add deduplication settings (frequency, keeping data) and Add setting to disable cleanup process https://github.com/Particular/NServiceBus.Persistence.Sql/pull/283
- [x] Doco https://github.com/Particular/docs.particular.net/pull/3788

**Comment by SzymonPobiega** [comment]
Also add an option to disable the outbox cleanup process.

**Comment by weralabaj** [comment]
That was done
