### ISSUE TITLE
SQL scripts don't get included when publishing

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.Persistence.Sql#211]
When performing a `dotnet publish`, the generated SQL scripts aren't copied to the output folder. If the user hasn't disabled auto-execution of the scripts, this means deploying the code in the publish folder will fail.

**Comment by weralabaj** [comment]
@kbaley I'm not 100% if my memory is correct, but I think in the end we agreed that this works as designed? Can we withdraw this issue?

**Comment by kbaley** [comment]
@weralabaj I agree with that. We state in the docs that scripts should be auto-executed only in development so I think it's okay not to include them explicitly in a deployment artifact. I've updated the [docs](https://docs.particular.net/persistence/sql/#script-creation) to clarify this.
