### ISSUE TITLE
When using SQL persistence in combination with other persistence: The solution throws System.Exception: 'ConnectionBuilder must be defined.'

### ISSUE THREAD

**Issue by jbakholt** [Particular/NServiceBus.Persistence.Sql#221]
When spinning up a MSMQ endpoint in a topshelf console app the app throws an exception: System.Exception: 'ConnectionBuilder must be defined.'

My app worked perfectly until I added the NServicebus.Persistence.Sql nuget package.  The MSMQ endpoint will not be using SqlPersistence but my plan is to spin up a second endpoint in the same host that uses SqlPersistence.

Repro:

1. New .NET 4.6.2 Console app
2. Set up topshelf
3. In the topshelf service class configure a MSMQ endpointconfiguration with InMemoryPersistence
4. Start the MSMQ endpoint by :   var endpointInstance = Endpoint.Start(endpointConfiguration).ConfigureAwait(false).GetAwaiter().GetResult();
5. Everything should work just fine.
6. Now add the NServicebus.Persistence.Sql nuget package
7. Run the app again.
8. "Hopefully" it throws the mentioned exception

**Comment by weralabaj** [comment]
@jbakholt Thanks for raising this! Which version of SQL persistence are you using?

**Comment by jbakholt** [comment]
Ups. Sorry for that. Version 2.1.4

**Comment by weralabaj** [comment]
@jbakholt We're backporting the fix for this issue here https://github.com/Particular/NServiceBus.Persistence.Sql/pull/223, I'll let you know when it's released.

**Comment by weralabaj** [comment]
Fixed and smoke tested in release 2.2

**Comment by weralabaj** [comment]
@jbakholt The fix is included in release 2.2.0, just published. Details [here](https://github.com/Particular/NServiceBus.Persistence.Sql/releases/tag/2.2.0).

**Comment by jbakholt** [comment]
Thx. Will check it out later.
