### ISSUE TITLE
3.0.0 packages have regressed compared to 2.2.1

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.Persistence.Sql#234]
I was looking over the 3.0.0 packages, and I've noticed the following problems compared to 2.2.1:

-  The NServiceBus dependency of the 2.2.1 package is `>= 6.2.0 && < 7.0.0`, but the 3.0.0 package is `>= 6.0.0`. It's missing the upper bound, and I suspect that if 2.2.1 had a minimum dependency on 6.2.0, that is also true for 3.0.0.

- The 2.2.1 MSBuild package included task assemblies for .NET Framework and .NET Core, but the .NET Core task assembly has been removed from the 3.0.0 package. This task assembly is needed so that someone could use `dotnet build` to build their project and have the MSBuild task work.

**Comment by SzymonPobiega** [comment]
Thanks @bording for checking this ❤️ . I've raised #236  and #237 to track these so I'll close this one.

**Comment by SzymonPobiega** [comment]
@bording when you are back after the Thanksgiving can you take a look at the 3.0.1 package to make sure we haven't missed anything?

**Comment by bording** [comment]
Looks like both of these issues have been addressed in the 3.0.1 packages!
