### ISSUE TITLE
Script generation targets file is missing an XML namespace causing VisualStudio 2015 build to fail

### ISSUE THREAD

**Issue by lnu** [Particular/NServiceBus.Persistence.Sql#239]
When I compile a project which references NServiceBus.Persistence.Sql.MsBuild with VS2015 I get this error:

![image](https://user-images.githubusercontent.com/1829553/33714027-c5f26b24-db4d-11e7-942b-798ec87f1ebd.png)

To make it work I have to edit the `NServiceBus.Persistence.Sql.MsBuild.targets` file and change this
```<Project>```
to
```<Project  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">```

Is there a more general fix for this?

**Comment by SzymonPobiega** [comment]
@lnu which version of SQL Persistent do you use?

**Comment by lnu** [comment]
I moved from 2.1.4 to 3.0.1

**Comment by lnu** [comment]
I have also another issue when migrating to 3.0.1. We're using tfs and when pushing the pdb to the symbol server I get this message:
```Indexed source information could not be retrieved from f:\Builds\5\20\Binaries\cdt.b2b\CdT.B2B.EUIPO\NServiceBus.Persistence.Sql.pdb. Error: Symbol indexes could not be retrieved.```

Would it be possible not to have the pdb in the main nuget pacakge but having a separate symbol package? 
I had the same issue with another library and we fixed it following this documentation:
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages

Apparently the indexing fails beause the pdb is in [portable format](https://github.com/Microsoft/vsts-tasks/issues/4567)

**Comment by SzymonPobiega** [comment]
@lnu 

Regarding the original issued, we're preparing a patch https://github.com/Particular/NServiceBus.Persistence.Sql/pull/242. Regarding the symbol packages I've asked the question internally as I am not the expert when it comes to nuget.

**Comment by SzymonPobiega** [comment]
Hi @lnu 

I've talked to our nuget gurus and the response was:
 * We don't want to split packages into binary and symbols because they are hard to work with using nuget tooling
 * You need to disable pushing of these packages to the symbol server until Microsoft supports the portable format

**Comment by SzymonPobiega** [comment]
@lnu I am closing this one to generate the release notes. If you strongly disagree with our stance on the symbol packages, please raise a separate issue.
