### ISSUE TITLE
Installer fails in web applications due to a problem localizing the generated script files

### ISSUE THREAD

**Issue by TechneWare** [Particular/NServiceBus.Persistence.Sql#245]
MsBuild 3.0x is working fine in normal services, console apps that sort of thing.
However, when using MsBuild 3.0x in web applications, it will generate an error in the web application that looks like the following:

System.Exception: Expected '[Path to Project]\NServiceBus.Persistence.Sql\MsSqlServer\Subscription_Create.sql' to exist

It appears to not be looking in [Path to Project]\bin\NServiceBus.Persistence.Sql\MsSqlServer\Subscription_Create.sql 

If you downgrade to MsBuild 2.x then it works fine again.

**Comment by lnu** [comment]
https://discuss.particular.net/t/sql-persistence-3-0-installer-and-website/230/2

**Comment by SzymonPobiega** [comment]
Closing to generate release notes.

**Comment by SzymonPobiega** [comment]
@TechneWare @lnu 3.0.4 has been released with the fix.
