### ISSUE TITLE
MSSqlServer: Create Subscription script is created twice

### ISSUE THREAD

**Issue by janv8000** [Particular/NServiceBus.Persistence.Sql#247]
https://github.com/Particular/NServiceBus.Persistence.Sql/blob/763a80d0955dfe6084d2c6804d856b2716ea01a1/src/ScriptBuilder/Writers/SubscriptionWriter.cs#L18

Call to BuildCreateScript should be replaced with BuildDropScript here.

**Comment by SzymonPobiega** [comment]
Good catch @janv8000 . I'll fix that!

**Comment by SzymonPobiega** [comment]
@janv8000 we're working on releasing the fix.

**Comment by SzymonPobiega** [comment]
The fix has been cherry picked to `release-4.0` branch.

**Comment by SzymonPobiega** [comment]
@janv8000 closing the issue in order to generate release notes.

**Comment by SzymonPobiega** [comment]
@janv8000 3.0.3 has been released with the fix. Thanks for raising the issue.
