### ISSUE TITLE
Dependency issue with v4.0.0-beta0004

### ISSUE THREAD

**Issue by danielwertheim** [Particular/NServiceBus.Persistence.Sql#253]
I have a custom NuGet package "Foo" targeting .NET Standard 2.0, this in turn has a dependency on "NServiceBus.Persistence.Sql (4.0.0-beta0004)"

When installing this to a .NET Core 2.0 Console application that targets .NET 4.7.1 the System.Data.SqlClient does not get resolved.

Create a .NET Core Console app and change to this in the `csproj`
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
```

Then install `NServiceBus.Persistence.Sql (4.0.0-beta0004)`.

Guess it's because of the condition here:
https://github.com/Particular/NServiceBus.Persistence.Sql/blob/develop/src/SqlPersistence/SqlPersistence.csproj#L20

**Comment by bording** [comment]
@danielwertheim I'm trying to understand your scenario a bit better. What actual problem are you running into? Are you getting error messages or runtime exceptions?

What is the code in your custom NuGet package doing and what are you doing in the console app?

**Comment by danielwertheim** [comment]
1) Create a .NET Standard 2.0 project e.g "Foo". Foo.csproj should look like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0-pre1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NServiceBus" Version="7.0.0-beta0012" />
    <PackageReference Include="NServiceBus.Persistence.Sql" Version="4.0.0-beta0004" />
    <PackageReference Include="NServiceBus.RabbitMQ" Version="5.0.0-beta0033" />
  </ItemGroup>

</Project>
```

2) Make use of some NServiceBus stuff in there, E.g:

```csharp
public static class TesterJoe
{
    public static async Task<IEndpointInstance> OpenAsync()
    {
        var cfg = new EndpointConfiguration("MyEndPoint");
        cfg.EnableInstallers();

        var transport = cfg.UseTransport<RabbitMQTransport>();
        transport.ConnectionString("host=localhost;");
        transport.UseDurableExchangesAndQueues(true);
        transport.UseConventionalRoutingTopology();

        var persistence = cfg.UsePersistence<SqlPersistence>();
        persistence.SqlDialect<SqlDialect.MsSqlServer>();
        persistence.ConnectionBuilder(() => new SqlConnection("data source=.\\sqlexpress2017;initial catalog=Foo;integrated security=SSPI;"));

        return await Endpoint.Start(cfg);
    }
}
```

3) Create a NuGet package of it

4) Create a .NET Core Console application, e.g. MyApp. Edit the MyApp.csproj to target .NET 4.7.1

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
</Project>
```

5) Build so that packages for 4.7.1 is restored

6) Reference the Foo-package created in step 3 (NOTE, not a project reference, but package), csproj of your console application should now look like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Foo" Version="1.0.0-pre1" />
  </ItemGroup>

</Project>
```

7) Make use of `TesterJoe` in e.g `Program.cs`

```csharp
using System;
using Foo;

namespace MyApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = TesterJoe.OpenAsync().Result;
            Console.WriteLine("Hello World!");
            Console.ReadKey();
        }
    }
}
```

The result is:

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MyApp.Program.Main(String[] args) in D:\temp\MyApp\MyApp\Program.cs:line 10

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

SOLUTION: Make `Foo` take a package dependency on `System.Data.SqlClient`.

**Comment by bording** [comment]
@danielwertheim Thanks for the detailed set of instructions to repro the problem you're seeing!

The reason you're having the problem is because of the target framework of your library. If you instead targeted `net471`, everything works properly. If you do want to continue to target `netstandard2.0` as well to ensure your library also works with .NET Core, then you could consider multitargeting by adding `<TargetFrameworks>net471;netstandard2.0</TargetFrameworks>` to your library's project file.

Our packages are multitargeted between `net452` and `netstandard2.0`, and we currently have dependencies scoped to only the target frameworks that actually require them. For example, System.Data.SqlClient isn't actually needed on the .NET Framework because the client is included as part of the framework.

Because of issues like the one you've encountered, we are considering making a change to our package dependencies to reference them for all frameworks. This would result in an extra shim assembly being in your bin folder, making your scenario work without needing to change your library's target framework.

**Comment by bording** [comment]
@danielwertheim For the 4.0.0-rc0002 package, you should no longer have the problem because we have adjusted the dependencies for the `net452` target.
