### ISSUE TITLE
When running integration tests with xunit on netcoreapp ScriptLocation returns an invalid path

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#312]
which means scripts dont get executed

`file:///C:/Users/simon/.nuget/packages/microsoft.testplatform.testhost/15.0.0/lib/netstandard1.5/testhost.dll`

![image](https://user-images.githubusercontent.com/122666/46011482-503f6b00-c109-11e8-9e3a-200bb1ac1caf.png)

**Comment by SimonCropp** [comment]
seems 

`Assembly.GetEntryAssembly()` returns the testhost location. which is invalid. While the `AppDomain.CurrentDomain.BaseDirectory` is correct but is doesnt get inside the if

**Comment by SimonCropp** [comment]
workaround: run them manually

```

    static Task RunSqlScripts(string endpointName, Func<DbConnection> connectionBuilder)
    {
        var baseDir = AppDomain.CurrentDomain.BaseDirectory;
        var scriptDir = Path.Combine(baseDir, "NServiceBus.Persistence.Sql", "MsSqlServer");

        return ScriptRunner.Install(
                sqlDialect: new SqlDialect.MsSqlServer(),
                tablePrefix: endpointName+"_",
                connectionBuilder: connectionBuilder,
                scriptDirectory: scriptDir,
                shouldInstallOutbox: false,
                shouldInstallSagas: true,
                shouldInstallSubscriptions: false,
                shouldInstallTimeouts: false);
    }
```

**Comment by mauroservienti** [comment]
@Particular/sqlpersistence-maintainers please take a look

**Comment by SimonCropp** [comment]
bump

**Comment by SzymonPobiega** [comment]
@SimonCropp I was looking at it and yeah, it seems there is an issue but I don't know yet how to fix it so we don't break all the strange cases. We'll likely look at this issue in detail before the next maintenance release.

**Comment by HEskandari** [comment]
The new command line tool can be used to generate scripts directly.
