### ISSUE TITLE
Script promotion unnecessarily deletes top-level folder containing the scripts

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#313]
```
Error SqlPersistenceTask: Failed to promote scripts to 'C:\Code\ProgramsManager\src\ProgramsManager\..\PromotedSqlScripts'. 
Error: Access to the path 'C:\Code\ProgramsManager\src\ProgramsManager\..\PromotedSqlScripts\MsSqlServer\Sagas' is denied.	ProgramsManager		1	
```

a full rebuild usually fixes it

**Comment by SimonCropp** [comment]
my guess would be to not delete the dirs [here](https://github.com/Particular/NServiceBus.Persistence.Sql/blob/develop/src/ScriptBuilder/ScriptWriter.cs#L55) but instead only delete the files

**Comment by SzymonPobiega** [comment]
@Particular/sqlpersistence-maintainers looks like a candidate for the maintenance release to me

**Comment by SimonCropp** [comment]
so this is almost a blocker. very annoying at the least. the rebuild only allows u to produce binaries, it doesnt prevent the same failure from occurring after a few more builds. so the experience is 

 * start debugging => build error
 * run tests => build error

**Comment by SzymonPobiega** [comment]
I've tried to repro it using the Simple sample but could not do it. Is there anything specific in your environment that I might be missing?

**Comment by SimonCropp** [comment]
i dont know how to produce a repro.

**Comment by SimonCropp** [comment]
any update on this?

**Comment by SzymonPobiega** [comment]
Without a repro we could not prioritize it and we tried hard but failed to catch it

**Comment by SimonCropp** [comment]
Isnt the fix, to only delete known files, safer? Ie if someone promotes scripts too high in the dir tree, u could be deleting critical files

**Comment by SzymonPobiega** [comment]
Right. We'll give it another try with the next release.

**Comment by SimonCropp** [comment]
I am curious what the hold is? My understanding of this bug is it is a trivial fix, delete the known files rather than the directory. Also by leaving this bug open so long you are knowingly leaving customer open to data loss if they use a promotion path that walks up too high. 

Is there something i am missing that makes this more complex to fix?

**Comment by SimonCropp** [comment]
would u like a repro that deletes everything on the c#?

**Comment by SimonCropp** [comment]
Any update on this or the pr I submitted?

**Comment by SzymonPobiega** [comment]
@SimonCropp I've relased it as 4.4.1
