### ISSUE TITLE
Refactor to simplify project structure

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#317]
With the MSBuild package no longer required, it may be possible to drastically simplify the project/packaging structure.

Also investigate if the ScriptBuilder package could be removed, perhaps by adding an InternalsVisibleTo for docs.

**Comment by tmasternak** [comment]
@DavidBoike do you have something concrete in mind? How much work would that be?

**Comment by DavidBoike** [comment]
Nothing concrete. @bording may have some more ideas.

The deal with ScriptBuilder is that what's in there shouldn't be a part of the public API, but it's bundled up into a NuGet package to be [used in a "test" in docs](https://github.com/Particular/docs.particular.net/blob/master/Snippets/SqlPersistence/SqlPersistence_5/ScriptWriter.cs) to generate the snippets that are used on [pages like this](https://docs.particular.net/persistence/sql/sqlserver-scripts). But what's interesting is now I see that the docs "test" I referred to [is using reflection](https://github.com/Particular/docs.particular.net/blob/master/Snippets/SqlPersistence/SqlPersistence_5/ScriptWriter.cs#L176-L180) to do it, and I don't think that was always the case.

But generally if we can avoid creating a NuGet package that users shouldn't use, that would probably be better.

**Comment by bording** [comment]
> With the MSBuild package no longer required, it may be possible to drastically simplify the project/packaging structure.

This has largely already been done.

> Also investigate if the ScriptBuilder package could be removed, perhaps by adding an InternalsVisibleTo for docs.

Being able to drop this as a separate package would be nice. Maybe even just integrate the `ScriptBuilderTask` project, so there's just one project.

The other thing we could do that would allow us to simplify some things would be to remove the "Integration" projects.

**Comment by SzymonPobiega** [comment]
Closing this one as we don't have immediate plans to act on this. The support for .NET framework is a blocker and we will come back to this in the future.

**Comment by bording** [comment]
@SzymonPobiega It's not clear to me what .NET Framework support has to do with this issue, or how it's a blocker to making the sort of changes being discussed here.

**Comment by SzymonPobiega** [comment]
@HEskandari could you elaborate on that? I don't remember the details.

**Comment by HEskandari** [comment]
@bording I don't know .NET Framework support is a _blocker_ per se, but we decoupled the cmd tool creation with project refactoring:

- We have created the dotnet tool for script generation
- The MSBuild task is still there, which is the main contributor to the complex project structure
- Probably makes sense before/when we drop .NET Framework.
