### ISSUE TITLE
Multi tenancy support

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.Persistence.Sql#320]
This was partially addressed by #284 but does not address the scenario where one endpoint instance may be serving multiple tenants that have different databases. I.e for tenant1 the Saga and business data might be located in tenant1_db and for tenant2 it might be in tenant2_db.

Something like this would be preferable: https://docs.particular.net/samples/outbox/multi-tenant/

Right now the connectionBulider is just a `Func<DbConnection>`. If it was a `Func<ContextBag, DbConnection>` that would allow me to access the tenantId from the `ContextBag` and open the appropriate database connection. Right now that does not appear possible.

I looked at implementing it, and it is straightforward for the most part. However, this won't play nicely with the OutboxCleaner, as this runs outside of the message context, so there would be no tenant identifier at this time.

**Comment by ramonsmits** [comment]
@markgould Do you mean that the approach of the multi-tenant outbox sample does not work for SQL Persistence?

Regarding the outbox cleaner, that is not multi-tenant aware and would require to know all tenant ID's. Probably a much better approach is to disable outbox cleanup in the endpoint instance and have a scheduled task run in the database server instance that does a similar query.

**Comment by markgould** [comment]
@ramonsmits  - yes that example will not work for SQL Persistence.

The work that was done so far has been very useful, as you can now specify a different a different connection string for subscriptions/timeouts. We use this to keep our subscriptions in a different database from the business data. This still requires an endpoint per tenant, when tenants have different databases.

Now what we are doing is looking at moving some of our on premise customers to the cloud, we would prefer not to have to run endpoint instances per tenant. With this we are also using the Azure Service Bus transport, so subscriptions are no longer a concern.

Right now you cannot customize the connection string based on message context information. The connection builder has no parameters passed to it.

Turning off the outbox cleaner is a good idea. I am going to submit a PR soon showing one way this could work.

**Comment by markgould** [comment]
@ramonsmits I was wrong, the NHibernate sample does actually work. It just feels a little odd using this AsyncLocal variable. In fact @danielmarbach has an article saying to avoid this! 

https://www.planetgeek.ch/2016/04/26/avoid-threadstatic-threadlocal-and-asynclocal-float-the-state-instead/

I will use this for now, but I would like to suggest someone look at the PR I submitted as an example of how the context information can flow through directly to the connection builder.

**Comment by ramonsmits** [comment]
@markgould I just saw your PR, I think it can serve as inspiration for a future version to pass a context to create a tenant specific connection. I agree that using AsyncLocal is potentially more vulnerable to errors if not managed correctly compared to passing a context reference.

Based on your comment I'll close this issue.

**Comment by SzymonPobiega** [comment]
@markgould the problem with the `AsyncLocal` hack is that the outbox cleanup would not work because it would need to get access to a list of connections for each tenant database. You need to disable the outbox cleanup and create a custom script that will take care of removing old outbox records.

You need to also make sure to override the connection builder for the `TimeoutManager` for the same reason.

**Comment by markgould** [comment]
@SzymonPobiega agreed. I have disabled Outbox Cleanup and will need to come up with a solution. I will likely look to use Elastic Database Jobs as this is all in Azure SQL. 

I am only using this with Azure Service Bus, so timeouts are handled natively by the transport. 

We are moving a few of our customers that all have their own on premise installations to Azure, so I'm making the endpoints multi-tenant capable rather than having to deploy instances for each customer.

**Comment by DavidBoike** [comment]
For anyone else finding this issue, multi-tenant support has been added to SQL Persistence 4.5.1.

See https://docs.particular.net/persistence/sql/multi-tenant
