### ISSUE TITLE
Support Newtonsoft.Json 12.0.1

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus.Persistence.Sql#322]
Adds support for Newtonsoft.Json version 12.0.1

---

Originally submitted by @gbiellem 
Newtonsoft.Json 12.0.1 is released but the dependency constraints on this are holding us back on 11

**Comment by SimonCropp** [comment]
given this will be binding redirect issues for most users, can we get this fast tracked

**Comment by SimonCropp** [comment]
any progress?

**Comment by SzymonPobiega** [comment]
@SimonCropp we're starting work on this.

**Comment by indualagarsamy** [comment]
Closing issue via PR #325
