### ISSUE TITLE
Unexpected issue with script generation

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.Persistence.Sql#332]
If you are referencing a package that then references NServiceBus.Persistence.Sql you will run into issues with sagas not being written, and the SqlPersistenceSettings attribute ignored.

We have an infrastructure library that references NServiceBus.Persistence.Sql and then our endpoints reference our infrastructure library (NuGet package). The workaround is to add a direct reference to NServiceBus.Persistence.Sql and then script generation will work correctly.

Not sure if this can be fixed or not, but may be worth noting in documentation to help anyone else out in future.

**Comment by SzymonPobiega** [comment]
@bording isn't that fixed with latest releases? I have faint memory that someone told me so.

**Comment by bording** [comment]
Yes, we have updated the package to use the `buildTransitive` feature, so if you're using VS 2019, this is now working properly.

Going to go ahead and close this since it is already done.

**Comment by markgould** [comment]
Awesome, thanks!
