### ISSUE TITLE
Test MariaDB/Aurora with the MySQL provider

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#339]
Replaces #16

Status as of June 8, 2018:

* Aurora
  * MySQL 5.7-compatible :+1:
  * PostgreSQL-compatible :+1:
* MariaDB
  * Use Cases selection screen
    * Production - Amazon Aurora (Recommended)
      * engine compatible with MySQL 5.6 :-1:
    * Production - MariaDB - uses MariaDB Community Edition, mariadb 10.2.12 is available, which would hopefully be :+1:
    * Dev/Test - same as non-Aurora Production above

**Comment by tmasternak** [comment]
@DavidBoike it looks that most of the work has been done here. How much work is still to be done here?

**Comment by DavidBoike** [comment]
That was just investigatory. I'm not sure I would feel comfortable saying we support either one unless we ran our test suite against them.

**Comment by aleksandr-samila** [comment]
I installed MariaDB on Docker but failed to set up access to it. Then I installed it locally and run MySql acceptance tests from the solution. Everything is green
![image](https://user-images.githubusercontent.com/5980232/106959975-1ef8f000-6744-11eb-98bf-9106623deaaa.png)

**Comment by aleksandr-samila** [comment]
AWS results:
Config 
![2021-02-04_223832](https://user-images.githubusercontent.com/5980232/106965718-b5c9aa80-674c-11eb-94f1-0a759a22703c.png)
MySql acceptance execution tests
![image](https://user-images.githubusercontent.com/5980232/106965852-f1647480-674c-11eb-954c-c3c3a1c9ce8a.png)

**Comment by aleksandr-samila** [comment]
Config (for PostgreSQL)
![2021-02-05_010118](https://user-images.githubusercontent.com/5980232/106968516-adc03980-6751-11eb-89c6-06d560428574.png)
PostgreSQL acceptance execution tests results (all are green)
![image](https://user-images.githubusercontent.com/5980232/106968968-9fbee880-6752-11eb-925a-7f1772ab07e2.png)

**Comment by mikeminutillo** [comment]
I raised three new issues to tackle making these officially supported. This will allow users to note their interest on these public issues.

- https://github.com/Particular/NServiceBus.Persistence.Sql/issues/626 MariaDB
- https://github.com/Particular/NServiceBus.Persistence.Sql/issues/627 Aurora with MySQL
- https://github.com/Particular/NServiceBus.Persistence.Sql/issues/628 Aurora with PostgreSQL
