### ISSUE TITLE
Oracle scripts can't be run easily from SQLPlus

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#362]
Our [guidance for installing scripts for Oracle](https://docs.particular.net/persistence/sql/install#manual-installation-mysql-oracle) involves a short C# snippet to execute the scripts while providing the table prefix. However many (most?) DBAs would probably prefer to execute scripts from the command line.

Our scripts, however, don't seem to support easily doing that. In working with a customer, we were unable to come up with a way to pass the `:1` parameter for the table prefix into the script.

```
SQL> variable 1 nvarchar2(25)
SQL> exec :1 := 'TLM_UnattendedWorkflow_'
SQL> start Outbox_Create.sql
SQL> /
```

with result:

```
SQL> variable 1 number
SP2-0553: Illegal variable name "1".
```

Most examples online involving passing parameters to SQLPlus use substitution variables (prefixed with an &) instead of bind variables (prefixed with :) and don't seem to work with bind variables. No doubt bind variables were chosen because the command is then parsed (and cached) once, and then the variables are bound later, which (at least) sounds more efficient. For hot path queries this is surely true. For DDL queries, it probably doesn't matter.

This may be my own poor understanding of Oracle at play (perhaps there's an easy syntax I'm missing) but we should consider if either changing the format of the scripts would prevent them from becoming blockers in more DevOps/DBA contexts.

**Comment by mikeminutillo** [comment]
Fixed for version 7.x on `master` in #600
Fixed for version 6.1 on `release-6.1` in #612
