### ISSUE TITLE
Support for Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#363]
Support for the [new Microsoft.Data.SqlClient](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/) library in the SQL Transport.

Related issue: [support in SQL Transport](https://github.com/Particular/NServiceBus.SqlServer/issues/506)

**Comment by DavidBoike** [comment]
The first step here is for us to analyze how this will affect both SQL Transport and Persistence, as well as customers that are still using (and have no reason to switch from) the original SqlClient.

**Comment by bording** [comment]
NServiceBus.Persistence.Sql 5.0 has been released, and it is compatible with `Microsoft.Data.SqlClient`.
