### ISSUE TITLE
Throw for missing [SqlSagaAttribute] at endpoint startup

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#38]
In my testing, I got the "Expected to find [SqlSagaAttribute]" exception not at startup, but at message receive time.

During development this is no fun, as we should be able to detect the condition at endpoint startup, but not throwing until a message for the saga is received makes it harder and take longer to find it, fix it, and "reset" what you were originally trying to do.

Not sure if this should be done via a traditional installer, or each and every time the endpoint starts up. There also may concerns about the binary package including a saga you're not actually planning to handle in that endpoint, although this seems a bit far fetched to me, as it would have to be handled somewhere, and likely using the same persister.

I would think the same check should be able to detect that the saga has no correlation id identified, which you would also receive as an error at message receive time if you had an empty `[SqlSaga]` defined.

**Comment by SimonCropp** [comment]
@DavidBoike how did u get this? it should throw a build error when u have no SqlSagaAttribute

**Comment by DavidBoike** [comment]
In my solution, I have a Conventions assembly configuring the persister in an INeedInitialization, and then an endpoint assembly (containing a saga) that references the Conventions assembly.

If you reference the MsBuild and base persister package in both projects, then you do get a compile error. Actually, I get two identical ones, might this be because it's happening on the MsBuild invocation from both assemblies involved?

> SqlPersistenceTask: Error in 'Shipping.ShippingPolicy'. Error:The type 'Shipping.ShippingPolicy' inherits from NServiceBus.Saga but is missing a [SqlSagaAttribute].

However, if you remove just the MsBuild package from the endpoint project, you won't get any errors until the saga attempts to receive a message:

```
System.Exception: Expected to find a [SqlSagaAttribute] on saga 'Shipping.ShippingPolicy'.
   at SqlSagaAttributeReader.GetSqlSagaAttributeData(Type sagaType) in C:\projects\nservicebus-sqlpersistence\SqlPersistence\Saga\SqlSagaAttributeReader.cs:line 12
   ...
```

This is the naive thing you might do if you tried to implement this persister by only including the NuGet packages on the Conventions assembly.

**Comment by SimonCropp** [comment]
Given this is only likely to happen when someone is initially setting up a project to use the sql persistence, it is not worth paying the price of scanning all types for saga metadata at startup. given the cost of that scanning would negatively impact all consumers on every startup. ie i agree with defensive coding but in this case it is too far down the path of optimising for people doing it wrong and forcing everyone to pay that price every time they debug.
