### ISSUE TITLE
Please add [ ] to all SQL scripts containing tablename to allow the usage of '.'

### ISSUE THREAD

**Issue by DocJames** [Particular/NServiceBus.Persistence.Sql#41]
Hi,

If possible, please add [ ] to all SQL scripts containing tablename to allow the usage of '.' 
And stop replacing '.' with '_' when using the Endpoint name to create tables.

E.g. change 

set @createTable = '
    create table ' + @tableName + '(
        Subscriber nvarchar(200) not null,

to

set @createTable = '
    create table [' + @tableName + '] (
        Subscriber nvarchar(200) not null,

in Create_MsSqlServer.sql.

I don't know if the same can/should be done for MySql.

Thanks,
Jimmy

**Comment by SimonCropp** [comment]
@DocJames what r u actually trying to achieve here? do you want to define a schema, hence the needs for periods in the name?

my understanding of naming things in sql is to avoid names that will require delimiters. hence the need for `[ ]` was not really evaluated.

**Comment by SimonCropp** [comment]
BTW i added doco on how to use a schema https://docs.particular.net/nservicebus/sql-persistence/#installation-table-prefix-database-schema

**Comment by DocJames** [comment]
@SimonCropp basically I would like table naming consistency when using both SQL Persistence and SQL Transport.

Our Endpoints are named like this: Esb.Endpoint.AggregatedPowerReadingEvent.2.0

Using SQL Persistence and SQL Transport gives the following tables:

Esb.Endpoint.AggregatedPowerReadingEvent.2.0
Esb.Endpoint.AggregatedPowerReadingEvent.2.0.Retries
Esb.Endpoint.AggregatedPowerReadingEvent.2.0.Timeouts
Esb.Endpoint.AggregatedPowerReadingEvent.2.0.TimeoutsDispatcher
Esb_Endpoint_AggregatedPowerReadingEvent_2_0_SubscriptionData
Esb_Endpoint_AggregatedPowerReadingEvent_2_0_TimeoutData

Using [ ] in all SQL Persistence scripts will make it possible to use '.' in the table name and thereby "group" all the related service tables together.

**Comment by SimonCropp** [comment]
replaced by https://github.com/Particular/NServiceBus.Persistence.Sql/issues/45 and  https://github.com/Particular/NServiceBus.Persistence.Sql/issues/44

**Comment by SimonCropp** [comment]
@DocJames hope to have v2 out within a week. there will be an upgrade guide showing the changes

**Comment by DocJames** [comment]
@SimonCropp Thanks
