### ISSUE TITLE
Drop support for Saga<T> as a base class

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#47]
i.e. drop support for this https://docs.particular.net/nservicebus/sql-persistence/saga#saga-definition

```
[SqlSaga(
     correlationProperty: nameof(SagaData.OrderId)
 )]
public class OrderSaga : Saga<OrderSaga.SagaData>,
```

and only allow this https://docs.particular.net/nservicebus/sql-persistence/saga#saga-definition-sqlsaga

```
[SqlSaga(
     correlationProperty: nameof(SagaData.OrderId)
 )]
public class OrderSaga : SqlSaga<OrderSaga.SagaData>,
```

Since inheriting from `Saga<T>`

 * forces duplication of `ToSaga` in mapping
 * requires duplicating the correlation property in the attribute and the mapping
 * is a more verbose way of achieving something we should only have one approach for.
 * supporting both means documenting both, and explain the difference when really people should always choose the less verbose option

**Comment by weralabaj** [comment]
I think it makes sense, having both seems to be really confusing for people.

**Comment by SzymonPobiega** [comment]
I am still a bit skeptical about this. I would like to treat the SQL persistence features as *enhancements* same way as progressive web apps treat features of modern browsers i.e. it would be cool if plain old saga could run with sql persistence.

Another idea would be to allow to specify the attributes outside of saga assembly like unobtrusive javascript.

I understand that some features are purely SQL-specific (e.g. finders) but don't like the need to depends on SQL persistence in my business entities (and we guide people to treat sagas as such).

**Comment by SimonCropp** [comment]
@SzymonPobiega 

>  it would be cool if plain old saga could run with sql persistence.

this is just not possible. well not possible in a way that allows us to reliable infer mapping  and detect edge cases

> don't like the need to depends on SQL persistence in my business entities (and we guide people to treat sagas as such).

In reality though changing a base class and having an attribute in no way.

Ideally i would like to see the core support the possibility of detecting mapping at compile time. but at the moment the current API does not allow us to do it
