### ISSUE TITLE
Scripts aren't copied to publish directory (publish no-build)

### ISSUE THREAD

**Issue by Donnatello** [Particular/NServiceBus.Persistence.Sql#490]
Hi,

I found a problem with the SQL-scripts when using the `dotnet publish --no-build` command - they are not copied to the publish directory.

I found this on my build server after upgrading from v.4.6 to v.6. And a quick search through the repository led me to the commit: https://github.com/Particular/NServiceBus.Persistence.Sql/commit/2148a5b35991e3235272d209179367c4123afbc0

I think the source of the problem is that `AfterCompile` is not used in case with `--no-build` flag.

Moreover, there is another problem associated with the same changes: https://discuss.particular.net/t/nservicebus-7-2-0-does-not-generate-saga-scripts-on-publish/1973

To fix the problem locally I used the following settings for my host project:
```
  <ItemGroup>
    <NsbSqlPersistenceScripts Include="$(ProjectDir)$(OutDir)NServiceBus.Persistence.Sql\**\*.sql" />
    <ContentWithTargetPath Include="@(NsbSqlPersistenceScripts)">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>NServiceBus.Persistence.Sql\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
```
And it solved both problems.

**Comment by WilliamBZA** [comment]
Thanks @Donnatello. We'll review your PR and get back to you :+1:

**Comment by bording** [comment]
Hi @Donnatello, I was able to reproduce the incorrect behavior when using the `--no-build` option.

I also took a look at your PR, and while that does work, it doesn't take into account how/when MSBuild evaluates item and property groups when they aren't inside a target.

I've opened #493 to address the problem and ensure everything is inside a target that can be run at the appropriate times.

**Comment by bording** [comment]
@Donnatello FYI I have edited your issue a bit to add our standard bug sections while keeping your original text at the bottom.
