### ISSUE TITLE
The new 'UseTransactionScope' option for outbox does not work as expected

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.Persistence.Sql#504]
We are running NServicebus 7.4.0 with `NServiceBus.Persistence.Sql`  6.0.2. We have recently activated `TransactionScope` as the transaction type for the outbox according [to the NServiceBus documentation](https://docs.particular.net/persistence/sql/outbox#transaction-type-transaction-scope). 

To my surprise, `Transaction.Current` is `null` in my message handler. Here's a sample app that can be used to reproduce the issue: https://github.com/pardahlman/nsb-trasaction-scope-repro

Have I missed something, or is this expected behavior?

**Comment by pardahlman** [comment]
I believe the issue is that the `TransactionScopeAsyncFlowOption.Enabled` option for a `TransactionScope` only works from outer-level to inner-level async methods (similar to flow restrictions in `AsyncLocal<T>`). When looking closer at how the transaction scope is used in the outbox, it is clear that that the message pipeline is a "sibbling method" rather than a child method to the code that creates the transaction scope.

To verify this, try running this app:

```csharp
using System;
using System.Threading.Tasks;
using System.Transactions;

namespace App
{
    internal static class Program
    {
        private static TransactionScope _transactionScope;

        private static async Task Main(string[] args)
        {
            await CreateTransactionScopeAndCallChildMethodAsync();
            Console.WriteLine($"Transaction scope in Main: {Transaction.Current}");
            await SecondLevelAsyncMethod("Main");
        }

        private static async Task CreateTransactionScopeAndCallChildMethodAsync()
        {
            _transactionScope = new TransactionScope(TransactionScopeOption.RequiresNew, TransactionScopeAsyncFlowOption.Enabled);
            Console.WriteLine($"Outer transaction scope method: {Transaction.Current}");
            await Task.Delay(TimeSpan.Zero);
            Console.WriteLine($"Outer transaction scope method after async/await: {Transaction.Current}");
            await SecondLevelAsyncMethod("transaction scope method");
        }

        private static async Task SecondLevelAsyncMethod(string calledFrom)
        {
            Console.WriteLine($"Second level method as child from {calledFrom}: {Transaction.Current}");
            await Task.Delay(TimeSpan.Zero);
            Console.WriteLine($"Second level method after async/await as child from {calledFrom}: {Transaction.Current}");
        }
    }
}
```

**Comment by danielmarbach** [comment]
@pardahlman you are correct this is how the TransactionScope floating with async works. I reviewed the code and indeed the current implementation is broken. We are doing some more further triaging on this one and will update you soon. 

We have already raised verification PRs for both [Sql Persistence](https://github.com/Particular/NServiceBus.Persistence.Sql/pull/505) as well as [NHibernate](https://github.com/Particular/NServiceBus.NHibernate/pull/466). Thanks for raising this!

**Comment by danielmarbach** [comment]
@pardahlman we are aiming at releasing this sometime tomorrow or friday given the criticality of this issue. Sorry for the inconvience. We will keep you up to date

**Comment by larsw** [comment]
Looking forward to the fix!

**Comment by pardahlman** [comment]
@danielmarbach thanks for the swift response, much appreciated 🙏

**Comment by danielmarbach** [comment]
@pardahlman @larsw we have released the fix

https://discuss.particular.net/t/nservicebus-persistence-sql-6-0-3-critical-patch-release-avaialble/2049

We found a similar problem in [Nhibernate and have fixed that too](https://discuss.particular.net/t/nservicebus-nhibernate-8-4-3-critical-patch-release-avaialble/2048).
