### ISSUE TITLE
Missing indexes for Subscriptions/Timeouts/Outbox

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#54]
In order to perform well, the Subscription/Timeout/Outbox tables need additional indexes, but currently they only generate primary key indexes in SQL Server. This may affect MySQL as well but I'm not sure.

### SubscriptionData
* Missing non-unique index on MessageType to use when querying for subscribers for a given message type.
  * NHibernate doesn't do this, but could potentially reverse the order of the primary key index (Subscriber ASC, MessageType ASC CLUSTERED) and then one index could serve both purposes.

### TimeoutData
* Missing non-unique index on Time, for query to find expired timeouts
* Missing non-unique index on SagaId, used for clearing timeouts from completed sagas

### OutboxData
* Current PK index (clustered) is on MessageId, which will result in a lot of index fragmentation
  * NHibernate version uses a auto-incrementing bigint Id column so that the rows will be written to data pages in order
  * NHibernate then has a UNIQUE non-clustered index on MessageId
* Missing Dispatched indexes that NH uses:
  * One on Dispatched (bool)
  * One on DispatchedAt (datetime)
  * If this is already a breaking change, it may be worth exploring replacing these 2 columns with just DispatchedAt and using IS NULL for comparisons in the queries.

**Comment by SimonCropp** [comment]
AFAIK the outbox clustered index is fixed in 2.0: https://docs.particular.net/nservicebus/upgrades/sqlpersistence-1.0.0-1.0.1#convert-outbox-index-to-nonclustered

i will look at the rest

**Comment by SimonCropp** [comment]
## 

> Missing non-unique index on MessageType to use when querying for subscribers for a given message type.

isnt this covered here https://github.com/Particular/NServiceBus.Persistence.Sql/blob/develop/src/ScriptBuilder/Subscription/Create_MsSqlServer.sql#L19  ?

## TimeoutData

hows this https://github.com/Particular/NServiceBus.Persistence.Sql/pull/55/commits/f0bf51c5f06ebb1b68dfa383d0454718973417cd  ?

## OutboxData

> Current PK index (clustered) is on MessageId

looks like it is nonclustered https://github.com/Particular/NServiceBus.Persistence.Sql/blob/develop/src/ScriptBuilder/Outbox/Create_MsSqlServer.sql#L13 ?

> Missing Dispatched indexes

https://github.com/Particular/NServiceBus.Persistence.Sql/pull/55/commits/9baaa1499fa1bb61fb6294f7ad70aaf1926df7d4
