### ISSUE TITLE
Use `QUOTENAME` for building the qualified table names.

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Persistence.Sql#57]

**Comment by weralabaj** [comment]
@SzymonPobiega is that for MySQL and MSSQL only? seems oracle is already doing it?

**Comment by SzymonPobiega** [comment]
@weralabaj I raised it while reviewing MSSQL stuff. I haven't looked at MySQL and I am not sure there is a `QUOTENAME` equivalent there.

**Comment by SimonCropp** [comment]
@SzymonPobiega @weralabaj does this need to be in the 2.2 milestone? give we now have a 3.0 pending i was wondering if we should just bump this to 3?

**Comment by weralabaj** [comment]
I don't have objections.

**Comment by SimonCropp** [comment]
given we will probably going beta on nuget in the next couple of days, is this going to make it in v3?

**Comment by SzymonPobiega** [comment]
After analyzing it, it seems that it is not really possible as the name of the table needs to be generated on the C# side. Closing.
