### ISSUE TITLE
Script creation does not work in .net Core/project.json

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/NServiceBus.Persistence.Sql#6]
Project.json does not support the MSBuild-Task. I am aware that this would be solved when the .net Core MSBuild-/csproj-Tooling is finished. Perhaps you could provide a powershell script or a console app in the meantime that does the same as the MSBuild-Task.

**Comment by SimonCropp** [comment]
the combo of csproj and project.json seems to be the current recommendation from MS. it is what most of their teams are using for development. eg EF https://github.com/aspnet/EntityFramework/tree/dev/src/Microsoft.EntityFrameworkCore

and that combo should support pulling in the msbuild task

**Comment by SimonCropp** [comment]
this might help http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/

**Comment by SimonCropp** [comment]
@Tobias-Gr any luck?

**Comment by Tobias-Gr** [comment]
The new csproj-tooling (or Visual Studio 2017) is not stable enough yet (at least in our experience). I'll try SqlPersistence again with .net Core when the next Visual Studio 2017 RC is released. It's OK for me to wait with this issue until then.

**Comment by SimonCropp** [comment]
Csproj and project json works fine in 2015

**Comment by SimonCropp** [comment]
did u try Csproj and project json ?

**Comment by Tobias-Gr** [comment]
We plan to migrate our project to VS 2017 and the new tooling in March or April. After migration we would try SqlPersistence again.

**Comment by SimonCropp** [comment]
@Tobias-Gr sounds like a good plan. please let me know how you go
