### ISSUE TITLE
Add official support for Amazon Aurora using MySQL dialect

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.Persistence.Sql#627]
In https://github.com/Particular/NServiceBus.Persistence.Sql/issues/339 we tested the SQL Persistence against AWS Aurora (MySQL compatibility) with the MySQL dialect. All tests passed.

In order to fully support this and add it to [our list of supported SQL implementations](https://docs.particular.net/persistence/sql/#supported-sql-implementations), we'd want to add it to the list of database engines that we test against as part of our continuous integration process.

**Comment by mauroservienti** [comment]
https://github.com/Particular/NServiceBus.Persistence.Sql/pull/1310 made it so that Aurora-related workflows are executed when tagging, and this during the release process. It’s been decided to not run them at every commit to avoid adding 51 more minutes to every build.
