### ISSUE TITLE
Add official support for Amazon Aurora using PostgreSQL dialect

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.Persistence.Sql#628]
In https://github.com/Particular/NServiceBus.Persistence.Sql/issues/339 we tested the SQL Persistence against AWS Aurora (PostgreSQL compatibility) with the PostgreSQL dialect. All tests passed.

In order to fully support this and add it to [our list of supported SQL implementations](https://docs.particular.net/persistence/sql/#supported-sql-implementations), we'd want to add it to the list of database engines that we test against as part of our continuous integration process.

**Comment by mauroservienti** [comment]
https://github.com/Particular/NServiceBus.Persistence.Sql/pull/1310%20made%20it%20so%20that%20Aurora-related%20workflows%20are%20executed%20when%20tagging,%20and%20this%20during%20the%20release%20process.%20It%E2%80%99s%20been%20decided%20to%20not%20run%20them%20at%20every%20commit%20to%20avoid%20adding%2051%20more%20minutes%20to%20every%20build.

**Comment by mauroservienti** [comment]
https://github.com/Particular/NServiceBus.Persistence.Sql/pull/1310 made it so that Aurora-related workflows are executed when tagging, and this during the release process. It’s been decided to not run them at every commit to avoid adding 51 more minutes to every build.

**Comment by udidahan** [comment]
Will they be run at some other schedule?

**Comment by mikeminutillo** [comment]
@udidahan They are scheduled to run once a week.
