### ISSUE TITLE
Outbox cleanup does full table scan on SQL Server

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.Persistence.Sql#66]
### What is the problem?

Currenly the Outbox on SQL Server creates two separate indexes on `Dispatched` and `DispatchedAt` columns.

Execution plan of the cleanup query:

```sql
delete top (@BatchSize) from table
where Dispatched = 'true'
    and DispatchedAt < @DispatchedBefore"
```

Indicates that a table scan is performed. All the other queries only use the primary key index (unique lookup by the primary key).

These two indexes are useless and have negative performance impact (they have to be updated on insert and when marking an Outbox record as dispatched).

### How to solve it?

A single filtered index will resolve it:

```sql
create index table_dispatched_idx on table (DispatchedAt) where Dispatched = 1
```

**Comment by MarcinHoppe** [comment]
@Particular/sqlpersistence-maintainers I am working on a PR to fix this.

**Comment by MarcinHoppe** [comment]
The PR #67 is ready to go.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe so we would have the same problems with NHibernate persistence over SQL Server?

**Comment by MarcinHoppe** [comment]
Potentially. The same indexes will likely be generated by NHibernate on Oracle.

I'd have to check the SQL generated by NHibernate.
