### ISSUE TITLE
Update to Newtonsoft.Json v10.0.1

### ISSUE THREAD

**Issue by gamblen** [Particular/NServiceBus.Persistence.Sql#81]
Would it be possible to get the NuGet package to allow v10.0.1 of Newtonsoft.Json?
Currently it is >= 9.0.0 & < 10.0.0

As NServiceBus.Newtonsoft.Json (v1.1.0) now requires >= 10.0.1 & < 11.0.0 the latest versions cannot be used in the same project.

**Comment by mikeminutillo** [comment]
@gamblen this change has been made and merged https://github.com/Particular/NServiceBus.Persistence.Sql/pull/61

It is waiting on the release of 2.0. 

@Particular/sqlpersistence-maintainers please chime in with a timeline on when 2.0 will be released.

**Comment by SimonCropp** [comment]
@gamblen 2.0 has been released. note there are some breaking changes https://docs.particular.net/nservicebus/upgrades/sqlpersistence-1to2 

Please let us know if need any help upgrading or the upgrade guide needs anything clarified
