### ISSUE TITLE
Sample for evolving saga data

### ISSUE THREAD

**Issue by Tobias-08** [Particular/NServiceBus.Persistence.Sql#826]
Hi,

do you have a working sample for evolving saga data? The [documentation](https://docs.particular.net/persistence/sql/saga#json-net-settings-custom-settings-version-specific-type-specific-deserialization-settings) gives an idea of the approach but leaves out the details.

My scenario is a breaking change in saga data (e. g. converting a `string`-Property to a `IList<string>`-Property). I would like to detect and convert (custom logic) old saga data while reading the first time and write back new/converted saga data after that.

Thanks,
Tobias

**Comment by mikeminutillo** [comment]
Hi Tobias. We don't have a sample for that specific scenario but it should be possible to do it by adding a custom json converter to the json serializer.

First off, you need a converter that can detect a list target and convert a single element into a list when it finds one. Something like this:

```csharp
class ElementConverter<T> : JsonConverter
{
  public override bool CanConvert(Type objectType)
  {
    return (objectType == typeof(IList<T>));
  }

  public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
  {
    var token = JToken.Load(reader);
    if(token.Type == JTokenType.Array)
    {
      return token.ToObject<List<T>>();
    }
    return new List<T> { token.ToObject<T>() };
  }

  public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
  {
     serializer.Serialize(writer, value);
  }
}
```

Then you'd need to add it to the NServiceBus saga persistence serializer.

```csharp
var settings = new JsonSerializerSettings
{
  Converters = {
    new ElementConverter<string>()
  }
};

var sagaSettings = persistence.SagaSettings();
sagaSettings.JsonSettings(settings);
```

With this in place, the system should be able to load the old single value into a List, and save the object with the list when it's done. Each time a saga instance is accessed it will be updated. Once all saga instances in the database have been converted, the custom converter can be removed.

If you're updating the file version of the saga assembly, then you can use the `JsonSettingsForVersion()` overload to only include the converter for older saga instances.

Let me know if that helps to get you unstuck.

**Comment by Tobias-08** [comment]
Hi @mikeminutillo,

thanks. Your snippets should get me started!

Tobias
