### ISSUE TITLE
Old correlation columns are not dropped on MySQL and SQL Server

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.Persistence.Sql#85]
### How to reproduce?

Walk through the [Transitioning Saga Correlation Ids](https://docs.particular.net/samples/sql-persistence/transitioning-correlation-ids/) sample.

#### MySQL

The `Correlation_OrderNumber` column is not removed. The corresponding index is correctly removed.

#### SQL Server

The `Correlation_OrderNumber` column is not removed. The corresponding index is not removed either.

**Comment by SzymonPobiega** [comment]
In SQLServer the root cause is that we look up the table in the `ALTER TABLE` builder by name with schema where name without schema is expected. 

Not sure yet what is the problem with MySQL.
