### ISSUE TITLE
Implement latest version check

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.Persistence.Sql#853]
Since only the [latest version of a tool is supported](https://docs.particular.net/nservicebus/tools/), the [NServiceBus.Persistence.Sql.CommandLine](https://www.nuget.org/packages/NServiceBus.Persistence.Sql.CommandLine) tool should have latest version check functionality like [Particular.AzureTable.Export does](https://github.com/Particular/Particular.AzureTable.Export/blob/20e77bd/src/Particular.AzureTable.Export/ToolVersion.cs#L25).

**Comment by danielmarbach** [comment]
Closing, see the reason mentioned [here](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/461#issuecomment-1290269697) (applies also for the persistence)
